### ISSUE TITLE
Feed failed to load

### ISSUE THREAD

**Issue by rs-anantmishra** [canonical-web-and-design/developer.ubuntu.com#349]
URL: https://developer.ubuntu.com/snapcraft
Running Ubuntu 17.10 on VirtualBox 

**Options -**
OS: 64Bit Linux [2.x/3.x/4.x]
CPU: AMD Phenom II X4 (4 cores assigned.) 
RAM: 3072MB assigned to VMachine.
VirtualHDD: Dynamic .vdi file / 20.00GB

![screenshot from 2018-02-19 22-02-56](https://user-images.githubusercontent.com/35563275/36388038-ae085fb6-15c0-11e8-8623-55e14e89e9b5.png)

**Comment by anthonydillon** [comment]
Thank you very much for reporting this issue. It has been triaged and will be actioned soon.

**Comment by nottrobin** [comment]
The issue here is that the feed is loaded from tutorials.ubuntu.com, and for some reason tutorials.ubuntu.com's certificate can't be verified by python in this particular context. Something about the specific python version running in developer.ubuntu.com's environment makes it bad at certificate verification. That environment is set up in the old Mojo way, so it's not trivial to change.

The quickest fix for this is to move developer.ubuntu.com to our Kubernetes cluster like most of our modern sites - where it can easily use a more modern version of Python. We can hopefully get this done this week.

**Comment by nottrobin** [comment]
This will be fixed [by switching over DNS to Kubernetes](https://github.com/canonical-webteam/deployment-configs/issues/120), which will happen soon.
